### ISSUE TITLE
Setting up the BananaModManager with Banana Mania

### ISSUE THREAD

**Issue by Jkryv3nchuk** [MorsGames/BananaModManager#1]
I'm getting a little confused when it comes to setting up the manager with my game. When selecting Super Monkey Ball: Banana Mania as the Current Game in the Settings menu, it tells me "Game files need to be extracted to enable mod support. This may take a few minutes, and some extra files might get downloaded. Do you want to continue?". I click "Yes" and then it wants me to select a bunch of files; Which files are the ones I need to select?

I tried following the installation instructions but it doesn't seem say anything about this ^

Thanks for your time!

**Comment by MorsGames** [comment]
That's definitely not intentional, have to placed all the files into the same folder as the game?

**Comment by Jkryv3nchuk** [comment]
Lol, I had the BananaModManager files in a folder inside of the smbbm folder; Once I took the files out of the folder it worked. Thank you!
