### ISSUE TITLE
Doesn't open on Steam Deck

### ISSUE THREAD

**Issue by coolpringles** [MorsGames/BananaModManager#10]
I'm not very experienced with the Steam Deck OS so I don't know what the barrier is, whether I configured Lutris wrong or if it's just not compatible, so it'd be nice to have some official word on this if possible.

Thanks

**Comment by No1129** [comment]
i was just going to post this

**Comment by iswimfly** [comment]
Currently there is no plan for Steam Deck support with how Banana Mod Manager is loaded. Maybe someday it'll happen, but for now there is no support so I'm going to close this.
