### ISSUE TITLE
Cannot launch mod manager after using it once.

### ISSUE THREAD

**Issue by XarceChronus** [MorsGames/BananaModManager#2]
After successfully using a mod and installing the manager it worked just fine but now even after restarting my PC it just won't open.. How does it break after one use??

**Comment by BeaverIAB** [comment]
I'm in the same boat. Launched it once and it worked fine and now it's broken. Redownloading hasn't fixed the issue. Launching as an administrator makes the window appear, albeit a window that doesn't show the content of my mods folder, but doing anything apart from switching tabs causes an unhandled exception.

**Comment by XarceChronus** [comment]
Fixed it by deleting mod folder that had no mods in it or was incompatible

**Comment by MorsGames** [comment]
It's likely because there was some kind of an issue with the config file. I will look into this for sure, or at the very least get it to show an error message.

**Comment by XarceChronus** [comment]
It just really doesn't like seeing folders without configs in mods folder I
think
