### ISSUE TITLE
Allow us to locate the game's executable in the settings

### ISSUE THREAD

**Issue by Rings4** [MorsGames/BananaModManager#3]
As title says.

**Comment by arandomguysomewhere** [comment]
The redesigned latest version does seem to allow it by specifying the game's install directory, I think this issue can be closed.

**Comment by Rings4** [comment]
> The redesigned latest version does seem to allow it by specifying the game's install directory, I think this issue can be closed.

Oh wow, finally this software is usable for me haha thanks for letting me know!

EDIT: This just makes the game crash during the loading screen now. Even with no mods installed. Had to reinstall the game to fix it.
